name: ricardos_utils
description: A set of utilities I use in my Flutter projects
version: 2.0.1
repository: https://github.com/ricardoboss/ricardos_utils

environment:
  sdk: '>=3.5.2 <4.0.0'
  flutter: ">=3.24.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  strict: ^2.1.0
