name: ricardos_utils
description: A set of utilities I use in my Flutter projects
version: 1.0.4
homepage: https://github.com/ricardoboss/ricardos_utils

environment:
  sdk: '>=3.5.2 <4.0.0'
  flutter: ">=3.24.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
